[colors.bright]
black      = '#767676'
red        = '#e74856'
green      = '#16c60c'
yellow     = '#f9f1a5'
blue       = '#3b78ff'
magenta    = '#b4009e'
cyan       = '#61d6d6'
white      = '#f2f2f2'

[colors.normal]
black      = '#0c0c0c'
red        = '#c50f1f'
green      = '#13a10e'
yellow     = '#c19c00'
blue       = '#0037da'
magenta    = '#881798'
cyan       = '#3a96dd'
white      = '#cccccc'

[colors.primary]
background = '#0c0c0c'
foreground = '#cccccc'

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = false
size = {{ .font.size }}

[font.bold]
family = {{ .font.name | quote }}
style = "Bold"

[font.bold_italic]
family = {{ .font.name | quote }}
style = "Bold Italic"

[font.italic]
family = {{ .font.name | quote }}
style = "Italic"

[font.normal]
family = {{ .font.name | quote }}
style = "Regular"

{{  if eq .chezmoi.os "windows" -}}
[terminal.shell]
{{ dict "program" (env "COMSPEC") | toToml }}
{{- end  }}

[window.dimensions]
columns = {{ .terminal.size.x }}
lines = {{ .terminal.size.y }}
