{{- $colorsBright :=
      (dict "black"      "#767676"
            "blue"       "#3b78ff"
            "cyan"       "#61d6d6"
            "green"      "#16c60c"
            "magenta"    "#b4009e"
            "red"        "#e74856"
            "white"      "#f2f2f2"
            "yellow"     "#f9f1a5") -}}

{{- $colorsNormal :=
      (dict "black"      "#0c0c0c"
            "blue"       "#0037da"
            "cyan"       "#3a96dd"
            "green"      "#13a10e"
            "magenta"    "#881798"
            "red"        "#c50f1f"
            "white"      "#cccccc"
            "yellow"     "#c19c00") -}}

{{- $colorsPrimary :=
      (dict "background" "#0c0c0c"
            "foreground" "#cccccc") -}}

{{- $colors :=
      (dict "bright"     $colorsBright
            "normal"     $colorsNormal
            "primary"    $colorsPrimary) -}}

{{- $env :=
      (dict "TERM"       "xterm-256color") -}}

{{- $fontBold       := (dict "family" .font.name "style" "Bold")        -}}
{{- $fontBoldItalic := (dict "family" .font.name "style" "Bold Italic") -}}
{{- $fontItalic     := (dict "family" .font.name "style" "Italic")      -}}
{{- $fontNormal     := (dict "family" .font.name "style" "Regular")     -}}

{{- $font :=
      (dict "bold"                $fontBold
            "bold_italic"         $fontBoldItalic
            "builtin_box_drawing" false
            "italic"              $fontItalic
            "normal"              $fontNormal
            "size"                .font.size) -}}

{{- $windowDimensions :=
      (dict "columns"    .terminal.size.x
            "lines"      .terminal.size.y) -}}

{{- $window :=
      (dict "dimensions" $windowDimensions) -}}

{{- $config :=
      (dict "colors" $colors
            "env"    $env
            "font"   $font
            "window" $window) -}}

{{- /* Use cmd.exe as the default shell on Windows. */ -}}
{{- if eq .chezmoi.os "windows" -}}
{{-   $config = merge $config
        (dict "terminal"
          (dict "shell"
            (dict "program" (env "COMSPEC")))) -}}
{{- end -}}

{{- /* Render the configuration as TOML. */ -}}
{{- $config | toToml -}}
