""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Startup

if has('vim_starting')
  set encoding=utf-8
  filetype indent plugin on
  syntax on
endif

scriptencoding utf-8

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""" description
set autochdir                                              " cd to current file
set autoread                                               " reload on change
set backspace=eol,indent,start                             " use backspace
set belloff=all                                            " no bell
set cindent                                                " indent c source
set colorcolumn=+1                                         " highlight next
set complete-=i                                            "
set display+=lastline                                      "
set display+=truncate                                      "
set fileformat=unix                                        " use lf
set fillchars+=vert:\ "                                    " no separators
set formatoptions+=jro                                     " use smart comments
set hidden                                                 " use hidden buffers
set history=1000                                           " max command history
set hlsearch                                               "
set ignorecase                                             " ignore pattern case
set incsearch                                              "
set infercase                                              " guess casing
set laststatus=2                                           " use status line
set listchars=tab:>\ ,trail:-,extends:>,precedes:<,nbsp:+  "
set mouse=a                                                " use mouse
set nofoldenable                                           "
set noshowmode                                             " no insert mode
set noswapfile                                             " no swap file
set nowrap                                                 "
set number                                                 " use line numbers
set numberwidth=5                                          " line number columns
set report=0                                               " always report
set scrolloff=1                                            " lines from cursor
set shiftwidth=0                                           " use tabstop value
set shortmess+=I                                           " no intro message
set sidescroll=1                                           "
set sidescrolloff=2                                        "
set smartcase                                              " use case for upper
set smarttab                                               " use smart tabs
set splitbelow                                             " split below
set splitright                                             " split right
set tabpagemax=50                                          " max tab count
set termguicolors                                          " use 24-bit colors
set textwidth=80                                           " max text width
set ttimeout                                               " wait for sequence
set ttimeoutlen=100                                        " wait 100 ms
set viminfo^=!                                             " use upper globals
set virtualedit=block                                      " block mode
set wildmenu                                               " use autocomplete
set wildmode=list:longest,full                             " autocompletion

if has('unnamedplus')
  set clipboard^=unnamed,unnamedplus
else
  set clipboard^=unnamed
endif

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Internal helper functions.

function! ExecuteFormatter(command)
  const l:tempfile = tempname()
  silent execute 'noautocmd write ' .. l:tempfile

  " Assumes that the file to be formatted should be the last argument.
  const l:error = system(join(a:command + [l:tempfile], ' '))

  if v:shell_error
    " This error is unfortunately hidden by the |write| confirmation message.
    " Use |messages| to examine previously given messages.
    echohl ErrorMsg
    echomsg a:command[0] .. ' (' .. v:shell_error .. '): ' .. l:error
    echohl None
  else
    1,$delete_
    silent execute '1read ' .. l:tempfile
    0delete_
  endif
  call delete(l:tempfile)
  return 0
endfunction

function! GetEncoding() abort
  return &fileencoding ? &fileencoding : &encoding
endfunction

function! GetFont() abort
{{- if eq .chezmoi.os "darwin" }}
  return '{{- print .font.name ":h" .font.size ",Monaco:h" .font.size -}}'
{{- else if eq .chezmoi.os "linux" }}
  return '{{- print .font.name " " .font.size ",Monospace " .font.size }}'
{{- else }}
  return '{{- print .font.name ":h" .font.size ",Consolas:h" .font.size -}}'
{{- end }}
endfunction

function! GetMode() abort
  let l:mode = {
        \ "\<C-s>": 'S-BLOCK',
        \ "\<C-v>": 'V-BLOCK',
        \ 'R': 'REPLACE',
        \ 'S': 'S-LINE',
        \ 'V': 'V-LINE',
        \ 'c': 'COMMAND',
        \ 'i': 'INSERT',
        \ 'n': 'NORMAL',
        \ 's': 'SELECT',
        \ 't': 'TERMINAL',
        \ 'v': 'VISUAL',
        \ }
  return get(l:mode, mode(), mode())
endfunction

function! StripTrailingEmptyLines() abort
  let l:view = winsaveview()
  keeppatterns v/\_s*\S/d
  call winrestview(l:view)
endfunction

function! StripTrailingWhitespace() abort
  let l:view = winsaveview()
  keeppatterns %s/\s\+$//e
  call winrestview(l:view)
endfunction

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Ensure a consistent look and feel across CUI and GUI modes.

if has('gui_running')
  set columns={{ .editor.size.x }}
  set lines={{ .editor.size.y }}

  set guioptions+=a
  set guioptions+=c
  set guioptions-=L
  set guioptions-=R
  set guioptions-=T
  set guioptions-=b
  set guioptions-=e
  set guioptions-=f
  set guioptions-=l
  set guioptions-=m
  set guioptions-=r

  " Set list of fonts in order of preference.
  let &g:guifont=substitute(&g:guifont, '^$', GetFont(), '')

  if has('win32')
    set linespace=0
    if has('directx')
      set renderoptions=type:directx
    endif
  endif

  highlight Normal guibg=Black guifg=White
else
  highlight Normal ctermbg=Black ctermfg=White

  " Support true color in terminals other than xterm (e.g. tmux).
  if &term ==# "screen-256color"
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
  endif
endif

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Refer to :highlight for a list of available colors.
" Select colors that look good with both :set bg=dark and :set bg=light.

highlight! link StatusLine   Question
highlight! link StatusLineNC Title

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""" left
set statusline=                                            " clear
set statusline+=%#WildMenu#                                " begin color
set statusline+=\                                          "   space
set statusline+=%{GetMode()}                               "   vim mode
set statusline+=\                                          "   space
set statusline+=%*                                         " end color
set statusline+=%{&paste?'\ PASTE':''}                     " paste mode
set statusline+=\                                          " space
set statusline+=%n:                                        " buffer number
set statusline+=\                                          " space
set statusline+=%<%t                                       " file name
set statusline+=\                                          " space
set statusline+=%m                                         " modified flag
set statusline+=\                                          " space

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""" right
set statusline+=%=                                         " fill
set statusline+=0x%02.B\                                   " current byte
set statusline+=\|\                                        " pipe & space
set statusline+=%{&ff}                                     " file format
set statusline+=\                                          " space
set statusline+=%{strlen(GetEncoding())?'\|\ ':''}         " pipe & space
set statusline+=%{GetEncoding()}                           " encoding
set statusline+=\                                          " space
set statusline+=%{strlen(&ft)?'\|\ ':''}                   " pipe & space
set statusline+=%{&ft}                                     " file type
set statusline+=%{strlen(&ft)?'\ ':''}                     " space
set statusline+=%#WildMenu#                                " begin color
set statusline+=\ %p%%\ %l:%c\                             "   position
set statusline+=%*                                         " end color

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

let mapleader = ','
let maplocalleader = ';'

{{- if eq .chezmoi.os "linux" }}

" Write the contents of the current buffer as the root user.
cnoremap w!! w !sudo tee > /dev/null %

{{- end }}

inoremap <silent> <Leader>" Æ
inoremap <silent> <Leader>' æ
inoremap <silent> <Leader>: Ø
inoremap <silent> <Leader>; ø
inoremap <silent> <Leader>E É
inoremap <silent> <Leader>[ å
inoremap <silent> <Leader>e é
inoremap <silent> <Leader>{ Å
inoremap jk <Esc>

" Use CTRL-L to clear the current highlight.
nnoremap <silent> <C-L> :noh<C-R>=has('diff')?'<Bar>dif':''<CR><CR><C-L>

" Bind j to gj and k to gk without messing up relative line jumps.
" https://old.reddit.com/r/vim/comments/jplc5x/_/gbfqm6y/
noremap <expr> j (v:count? 'j' : 'gj')
noremap <expr> k (v:count? 'k' : 'gk')

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Load matchit.vim, but only if the user hasn't installed a newer version.

if !exists('g:loaded_matchit') && findfile('plugin/matchit.vim', &rtp) ==# ''
  runtime! macros/matchit.vim
endif

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Enable the :Man command shipped with Vim's man filetype plugin.

if exists(':Man') != 2 && !exists('g:loaded_man') && &filetype !=? 'man'
  runtime ftplugin/man.vim
endif

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Custom autocommands.

function! FormatBuffer()
  const l:view = winsaveview()
  normal gggqG
  call winrestview(l:view)
endfunction

" Format the buffer in a temporary file using a |formatexpr|.
" https://vi.stackexchange.com/a/42361
function! ShellFormat()
  const l:l1 = v:lnum
  const l:l2 = (v:lnum + v:count) - 1
  const l:lines = getline(l:l1, l:l2)
  const l:tempfile = tempname()

  call writefile(l:lines, l:tempfile)

function! ShellFormat()
  " Map b:current_syntax from $VIMRUNTIME/syntax/sh.vim to shfmt:
  const l:dialect = {
        \ 'bash':  'bash',
        \ 'ksh':   'auto',
        \ 'posix': 'posix',
        \ 'sh':    'posix',
        \ }

  const l:command = [
        \ &formatprg,
        \ '-bn',
        \ '-ci',
        \ '-i=' .. &tabstop,
        \ '-ln=' .. get(l:dialect, b:current_syntax, 'auto'),
        \ '-s',
        \ '-sr',
        \ '-w',
        \ ]

  return ExecuteFormatter(l:command)
endfunction

augroup vimrc.custom
  autocmd!

  " Remove trailing whitespace on save (unless binary)
  " https://vi.stackexchange.com/a/456
  autocmd BufWritePre *
        \ if &binary == 0                    |
        \   if empty(&formatprg)             |
        \     call StripTrailingWhitespace() |
        \   else                             |
        \     call FormatBuffer()            |
        \   endif                            |
        \ endif

  autocmd BufNewFile,BufRead *.sls,.clang-format
        \ setfiletype yaml

  autocmd BufWritePost $MYVIMRC
        \ source % |
        \ redraw!  |
        \ redrawstatus!

  autocmd FileType c,cpp
        \ if executable('clang-format') |
        \   setlocal formatprg=clang-format |
        \ endif

  autocmd FileType bash,json,sh,swayconfig,vim,yaml
        \ setlocal expandtab     |
        \ setlocal softtabstop=2 |
        \ setlocal tabstop=2

  autocmd FileType bash,sh
        \ if executable('shfmt')              |
        \   setlocal formatprg=shfmt          |
        \   setlocal formatexpr=ShellFormat() |
        \ endif

  autocmd FileType vim
        \ setlocal keywordprg=:help

  autocmd FileType markdown,text
        \ setlocal linebreak      |
        \ setlocal showbreak=+++\ |
        \ setlocal textwidth=0    |
        \ setlocal wrap

  if exists(':Man') == 2
    autocmd FileType c,cpp,sh setlocal keywordprg=:Man
  endif
augroup end

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Allow local overrides.

if filereadable(expand('~/.vimrc.local'))
  source ~/.vimrc.local
endif

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
