set clipboard^=unnamed,unnamedplus
set colorcolumn=+1
set hidden
set ignorecase
set infercase
set magic
set mouse=a
set nofoldenable
set notimeout
set nowrap
set number
set numberwidth=5
set report=0
set scrolloff=5
set shortmess+=I
set smartcase
set splitbelow
set splitright
set termguicolors
set virtualedit=block
set wildmode=list:longest,full
