""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Startup

if has('vim_starting')
  set encoding=utf-8
  filetype indent plugin on
  syntax on
endif

scriptencoding utf-8

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""" description
set autoread                                               " reload on change
set backspace=eol,indent,start                             " use backspace
set belloff=all                                            " no bell
set cindent                                                " indent c source
set clipboard^=unnamed,unnamedplus                         " system clipboard
set colorcolumn=+1                                         " highlight next
set complete-=i                                            "
set display+=lastline                                      "
set display+=truncate                                      "
set fileformat=unix                                        " use lf
set fillchars+=vert:\ "                                    " no separators
set formatoptions+=jro                                     " use smart comments
set hidden                                                 " use hidden buffers
set history=1000                                           " max command history
set hlsearch                                               "
set ignorecase                                             " ignore pattern case
set incsearch                                              "
set infercase                                              " guess casing
set laststatus=2                                           " use status line
set listchars=tab:>\ ,trail:-,extends:>,precedes:<,nbsp:+  "
set mouse=a                                                " use mouse
set nofoldenable                                           "
set noshowmode                                             " no insert mode
set noswapfile                                             " no swap file
set nowrap                                                 "
set number                                                 " use line numbers
set numberwidth=5                                          " line number columns
set report=0                                               " always report
set scrolloff=1                                            " lines from cursor
set shiftwidth=0                                           " use tabstop value
set shortmess+=I                                           " no intro message
set sidescroll=1                                           "
set sidescrolloff=2                                        "
set smartcase                                              " use case for upper
set smarttab                                               " use smart tabs
set splitbelow                                             " split below
set splitright                                             " split right
set tabpagemax=50                                          " max tab count
set termguicolors                                          " use 24-bit colors
set textwidth=80                                           " max text width
set ttimeout                                               " wait for sequence
set ttimeoutlen=100                                        " wait 100 ms
set viminfo^=!                                             " use upper globals
set virtualedit=block                                      " block mode
set wildmenu                                               " use autocomplete
set wildmode=list:longest,full                             " autocompletion

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Internal helper functions.

function! GetEncoding() abort
  return &fileencoding ? &fileencoding : &encoding
endfunction

function! GetFont() abort
{{- $font := print .font.name ":h" .font.size }}
  if has('mac')
    return '{{ $font }},Monaco:h{{- .font.size -}}'
  elseif has('win32')
    return '{{ $font }},Consolas:h{{- .font.size -}}'
  else
    return '{{ $font }},Monospace Medium:h{{- .font.size -}}'
  endif
endfunction

function! GetMode() abort
  let l:mode = {
        \ "\<C-s>": 'S-BLOCK',
        \ "\<C-v>": 'V-BLOCK',
        \ 'R': 'REPLACE',
        \ 'S': 'S-LINE',
        \ 'V': 'V-LINE',
        \ 'c': 'COMMAND',
        \ 'i': 'INSERT',
        \ 'n': 'NORMAL',
        \ 's': 'SELECT',
        \ 't': 'TERMINAL',
        \ 'v': 'VISUAL',
        \ }
  return get(l:mode, mode(), mode())
endfunction

function! StripTrailingWhitespace() abort
  let l:view = winsaveview()
  keeppatterns %s/\s\+$//e
  call winrestview(l:view)
endfunction

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Ensure a consistent look and feel across CUI and GUI modes.

if has('gui_running')
  set columns={{ .editor.size.x }}
  set lines={{ .editor.size.y }}

  set guioptions+=a
  set guioptions+=c
  set guioptions-=L
  set guioptions-=R
  set guioptions-=T
  set guioptions-=b
  set guioptions-=e
  set guioptions-=f
  set guioptions-=l
  set guioptions-=m
  set guioptions-=r

  " Set list of fonts in order of preference.
  let &g:guifont=substitute(&g:guifont, '^$', GetFont(), '')

  if has('win32')
    set linespace=0
    if has('directx')
      set renderoptions=type:directx
    endif
  endif

  highlight Normal guibg=Black guifg=White
else
  highlight Normal ctermbg=Black ctermfg=White
endif

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Refer to :highlight for a list of available colors.
" Select colors that look good with both :set bg=dark and :set bg=light.

highlight! link StatusLine   Question
highlight! link StatusLineNC Title

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""" left
set statusline=                                            " clear
set statusline+=%#WildMenu#                                " begin color
set statusline+=\                                          "   space
set statusline+=%{GetMode()}                               "   vim mode
set statusline+=\                                          "   space
set statusline+=%*                                         " end color
set statusline+=\                                          " space
set statusline+=%n:                                        " buffer number
set statusline+=\                                          " space
set statusline+=%<%t                                       " file name
set statusline+=\                                          " space
set statusline+=%m                                         " modified flag
set statusline+=\                                          " space

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""" right
set statusline+=%=                                         " fill
set statusline+=0x%02.B\                                   " current byte
set statusline+=\|\                                        " pipe & space
set statusline+=%{&ff}                                     " file format
set statusline+=\                                          " space
set statusline+=%{strlen(GetEncoding())?'\|\ ':''}         " pipe & space
set statusline+=%{GetEncoding()}                           " encoding
set statusline+=\                                          " space
set statusline+=%{strlen(&ft)?'\|\ ':''}                   " pipe & space
set statusline+=%{&ft}                                     " file type
set statusline+=%{strlen(&ft)?'\ ':''}                     " space
set statusline+=%#WildMenu#                                " begin color
set statusline+=\ %p%%\ %l:%c\                             "   position
set statusline+=%*                                         " end color

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

let mapleader = ','
let maplocalleader = ';'

inoremap <silent> <Leader>" Æ
inoremap <silent> <Leader>' æ
inoremap <silent> <Leader>: Ø
inoremap <silent> <Leader>; ø
inoremap <silent> <Leader>E É
inoremap <silent> <Leader>[ å
inoremap <silent> <Leader>e é
inoremap <silent> <Leader>{ Å
inoremap jk <Esc>

" Use CTRL-L to clear the current highlight.
nnoremap <silent> <C-L> :noh<C-R>=has('diff')?'<Bar>dif':''<CR><CR><C-L>

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Load matchit.vim, but only if the user hasn't installed a newer version.

if !exists('g:loaded_matchit') && findfile('plugin/matchit.vim', &rtp) ==# ''
  runtime! macros/matchit.vim
endif

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Enable the :Man command shipped with Vim's man filetype plugin.

if exists(':Man') != 2 && !exists('g:loaded_man') && &filetype !=? 'man'
  runtime ftplugin/man.vim
endif

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Custom autocommands.

augroup vimrc.custom
  autocmd!

  " Remove trailing whitespace on save (unless binary or Markdown).
  " https://vi.stackexchange.com/a/456
  autocmd BufWritePre *
        \ if !&binary && &filetype !=# 'markdown' |
        \   call StripTrailingWhitespace() |
        \ endif

  autocmd BufNewFile,BufRead *.sls,.clang-format setfiletype yaml
  autocmd BufWritePost $MYVIMRC source % | redraw! | redrawstatus!
  autocmd FileType json,sh,vim,yaml setlocal expandtab softtabstop=2 tabstop=2
  autocmd FileType vim setlocal keywordprg=:help

  if exists(':Man') == 2
    autocmd FileType c,cpp,sh setlocal keywordprg=:Man
  endif
augroup end

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Allow local overrides.

if filereadable(expand('~/.vimrc.local'))
  source ~/.vimrc.local
endif

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

